# -*- coding: utf-8 -*-
"""Prak8RafaAgilMahendra_G.211.25.0056.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H9ntQ9ckgld3nWJyO1iK8ToWRcEFyCPX

Analisis Kompleksitas
Kompleksitas waktu = O(2ⁿ)
Kompleksitas ruang = O(n)
"""

def fib_recursive(n):
    if n <= 1:
        return n
    return fib_recursive(n - 1) + fib_recursive(n - 2)

n = 10
print("Fibonacci:", fib_recursive(n))

"""Analisis Kompleksitas

Setiap nilai dihitung satu kali.
Kompleksitas waktu = O(n)
Kompleksitas ruang = O(n)
"""

memo = {}

def fib_memo(n):
    if n in memo:
        return memo[n]

    if n <= 1:
        return n

    memo[n] = fib_memo(n - 1) + fib_memo(n - 2)
    return memo[n]

n = 50
print("Fibonacci:", fib_memo(n))

"""Analisis Kompleksitas

Loop berjalan sebanyak n kali.
Kompleksitas waktu = O(n)
Kompleksitas ruang = O(n)
"""

def fib_dp(n):
    if n <= 1:
        return n

    dp = [0] * (n + 1)

    dp[0] = 0
    dp[1] = 1

    for i in range(2, n + 1):
        dp[i] = dp[i - 1] + dp[i - 2]

    return dp[n]

n = 50
print("Fibonacci DP:", fib_dp(n))

"""Analisis Kompleksitas
Kompleksitas waktu = O(n)
Kompleksitas ruang = O(1)
Karena hanya menggunakan dua variabel
"""

def fib_optimized(n):
    if n <= 1:
        return n

    a = 0
    b = 1

    for i in range(2, n + 1):
        a, b = b, a + b

    return b

n = 50
print("Optimized Fibonacci:", fib_optimized(n))

"""Analisis Kompleksitas

Jika:
n = jumlah jenis koin
k = jumlah koin yang dipilih

Maka:
Kompleksitas waktu = O(n + k)
Kompleksitas ruang = O(k)
"""

def coin_change_greedy(coins, amount):
    coins.sort(reverse=True)

    result = []

    for coin in coins:
        while amount >= coin:
            amount -= coin
            result.append(coin)

    return result

coins = [100, 50, 25, 10, 5, 1]
amount = 289

hasil = coin_change_greedy(coins, amount)

print("Koin digunakan:", hasil)
print("Jumlah koin:", len(hasil))

"""Analisi Kompleksitas
Kompleksitas waktu = O(n × A)
Kompleksitas ruang = O(A)
"""

def count_ways(coins, amount):
    dp = [0] * (amount + 1)

    dp[0] = 1

    for coin in coins:
        for i in range(coin, amount + 1):
            dp[i] += dp[i - coin]

    return dp[amount]

coins = [1, 2, 5]
amount = 5

print("Jumlah kombinasi:", count_ways(coins, amount))