# -*- coding: utf-8 -*-
"""Praktikum4RafaAgilMahendra_G.211.25.0056.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18PF_VJCqwoQjQk3dDrEz4XyMtwFgLmeX

linear Search


Best Case	O(1)
Average Case	O(n)
Worst Case	O(n)
"""

def linear_search(data, target):
    for i in range(len(data)):
        if data[i] == target:
            return i
    return -1

data = [10, 20, 30, 40, 50]

cari = 30
hasil = linear_search(data, cari)

if hasil != -1:
    print(hasil)
else:
    print("Data tidak ditemukan")

"""Binary Search Iteratif

Best Case	O(1)
Average Case	O(log n)
Worst Case	O(log n)
"""

def binary_search(data, target):
    kiri = 0
    kanan = len(data) - 1

    while kiri <= kanan:
        tengah = (kiri + kanan) // 2

        if data[tengah] == target:
            return tengah
        elif data[tengah] < target:
            kiri = tengah + 1
        else:
            kanan = tengah - 1

    return -1

data = [10, 20, 30, 40, 50]

cari = 40
hasil = binary_search(data, cari)

if hasil != -1:
    print(hasil)
else:
    print("Data tidak ditemukan")

"""Binary Search Rekursif

Best Case	O(1)
Average Case	O(log n)
Worst Case	O(log n)
"""

def binary_search_rekursif(data, kiri, kanan, target):

    if kiri > kanan:
        return -1

    tengah = (kiri + kanan) // 2

    if data[tengah] == target:
        return tengah

    elif data[tengah] < target:
        return binary_search_rekursif(data, tengah + 1, kanan, target)

    else:
        return binary_search_rekursif(data, kiri, tengah - 1, target)


data = [10, 20, 30, 40, 50]

hasil = binary_search_rekursif(data, 0, len(data)-1, 20)

if hasil != -1:
    print(hasil)
else:
    print("Data tidak ditemukan")

"""Jump Search"""

import math

def jump_search(data, target):

    n = len(data)
    langkah = int(math.sqrt(n))
    awal = 0

    while awal < n and data[min(langkah, n) - 1] < target:
        awal = langkah
        langkah += int(math.sqrt(n))

        if awal >= n:
            return -1

    for i in range(awal, min(langkah, n)):
        if data[i] == target:
            return i

    return -1


data = [10, 20, 30, 40, 50, 60, 70]

hasil = jump_search(data, 60)

if hasil != -1:
    print(hasil)
else:
    print("Data tidak ditemukan")

"""Interpolation Search"""

def interpolation_search(data, target):

    low = 0
    high = len(data) - 1

    while low <= high and target >= data[low] and target <= data[high]:

        if low == high:
            if data[low] == target:
                return low
            return -1

        posisi = low + ((target - data[low]) * (high - low) //
                         (data[high] - data[low]))

        if data[posisi] == target:
            return posisi

        elif data[posisi] < target:
            low = posisi + 1

        else:
            high = posisi - 1

    return -1


data = [10, 20, 30, 40, 50]

hasil = interpolation_search(data, 50)

if hasil != -1:
    print(hasil)
else:
    print("Data tidak ditemukan")