# -*- coding: utf-8 -*-
"""Prak1KompleksitasWaktu_RafaAgilM_g.211.25.0056.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jaf5WivX-3sJO6g7LjQXVgtha1X9Zjc7
"""

def factorial(n):
    if n == 0:
        return 1
    else:
        res = 1
        for i in range(1, n + 1):
            res *= i
        return res

number = 10
result = factorial(number)
print(f"Faktorial dari {number} adalah {result}")