# -*- coding: utf-8 -*-
"""Prak6RafaAgilMahendra_G.211.25.0056.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JkWhQP1z-KtPB-2DxKDk8FyGm2wAwIJO
"""

def fibonacci(n):
    if n <= 1:
        return n

    return fibonacci(n - 1) + fibonacci(n - 2)

n = 6
print("Fibonacci ke-", n, "=", fibonacci(n))

def subset(data, hasil=[]):
    if len(data) == 0:
        print(hasil)
        return

    subset(data[1:], hasil)
    subset(data[1:], hasil + [data[0]])

data = [1, 2, 3]
subset(data)

def binary_string(n, hasil=""):
    if n == 0:
        print(hasil)
        return

    binary_string(n - 1, hasil + "0")
    binary_string(n - 1, hasil + "1")

binary_string(3)