# -*- coding: utf-8 -*-
"""Prak7RafaAgilMahendra_G.211.25.0056.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eZRRAjcYNGgZC8pkmhagAgjow24gSS_r
"""

def pca(data):
    mean_x = sum(row[0] for row in data) / len(data)
    mean_y = sum(row[1] for row in data) / len(data)

    centered = [[x - mean_x, y - mean_y] for x, y in data]

    n = len(data)
    cov_xx = sum(x*x for x, y in centered) / (n - 1)
    cov_yy = sum(y*y for x, y in centered) / (n - 1)
    cov_xy = sum(x*y for x, y in centered) / (n - 1)

    vx, vy = 1, 1

    for _ in range(20):
        new_vx = cov_xx * vx + cov_xy * vy
        new_vy = cov_xy * vx + cov_yy * vy

        norm = (new_vx**2 + new_vy**2) ** 0.5
        vx = new_vx / norm
        vy = new_vy / norm

    hasil = []
    for x, y in centered:
        hasil.append(x * vx + y * vy)

    return hasil


data = [
    [2.5, 2.4],
    [0.5, 0.7],
    [2.2, 2.9],
    [1.9, 2.2],
    [3.1, 3.0]
]

print(pca(data))