# -*- coding: utf-8 -*-
"""Prak3RafaAgilMahendra_g.211.25.0056.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15XzfwNsVG7vkhJ-1XqB4DeKJexaIy2xs

DIJKSTRA(Graf, sumber)

Untuk setiap simpul v pada graf:
    jarak[v] = tak hingga
    dikunjungi[v] = false

jarak[sumber] = 0

Ulangi sebanyak jumlah simpul:
    pilih simpul u yang memiliki jarak terkecil
    dan belum dikunjungi

    tandai u sebagai dikunjungi

    Untuk setiap tetangga v dari u:
        jika jarak[u] + bobot(u,v) < jarak[v] maka
            jarak[v] = jarak[u] + bobot(u,v)

Tampilkan jarak terpendek dari sumber ke semua simpul
"""

def dijkstra(graf, awal):
    jarak = {}

    for simpul in graf:
        jarak[simpul] = float('inf')

    jarak[awal] = 0
    dikunjungi = []

    while len(dikunjungi) < len(graf):

        kandidat = None

        for simpul in graf:
            if simpul not in dikunjungi:
                if kandidat is None or jarak[simpul] < jarak[kandidat]:
                    kandidat = simpul

        dikunjungi.append(kandidat)

        for tetangga, bobot in graf[kandidat].items():
            jarak_baru = jarak[kandidat] + bobot

            if jarak_baru < jarak[tetangga]:
                jarak[tetangga] = jarak_baru

    return jarak


graf = {
    'A': {'B': 4, 'C': 2},
    'B': {'A': 4, 'C': 1, 'D': 5},
    'C': {'A': 2, 'B': 1, 'D': 8, 'E': 10},
    'D': {'B': 5, 'C': 8, 'E': 2},
    'E': {'C': 10, 'D': 2}
}

hasil = dijkstra(graf, 'A')

print("Jarak terpendek dari A:")
for simpul in hasil:
    print(simpul, "=", hasil[simpul])