# -*- coding: utf-8 -*-
"""prak2RafaAgilmahendra_G.211.25.0056.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WS4dCSCdI9yhWLgxCif0JkJmFRxEvKwT

PSEUDOCODE

Insert(data):

    Buat node baru Z
    warna(Z) ← MERAH

    Cari posisi yang sesuai seperti Binary Search Tree
    Masukkan Z ke dalam pohon

    Selama warna(parent(Z)) = MERAH

        Jika parent(Z) berada di sisi kiri dari parent(parent(Z))

            U ← node lain yang sejajar dengan parent(Z)

            Jika warna(U) = MERAH

                warna(parent(Z)) ← HITAM
                warna(U) ← HITAM
                warna(parent(parent(Z))) ← MERAH

                Z ← parent(parent(Z))

            Jika warna(U) = HITAM

                Jika Z berada di sisi kanan parent(Z)

                    Z ← parent(Z)
                    RotasiKiri(Z)

                warna(parent(Z)) ← HITAM
                warna(parent(parent(Z))) ← MERAH

                RotasiKanan(parent(parent(Z)))

        Jika parent(Z) berada di sisi kanan dari parent(parent(Z))

            Lakukan langkah yang sama secara simetris warna (root)<- Hitam
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.color = "RED"
        self.left = None
        self.right = None
        self.parent = None


class RedBlackTree:
    def __init__(self):
        self.root = None

    def rotate_left(self, x):
        y = x.right
        x.right = y.left

        if y.left:
            y.left.parent = x

        y.parent = x.parent

        if x.parent is None:
            self.root = y
        elif x == x.parent.left:
            x.parent.left = y
        else:
            x.parent.right = y

        y.left = x
        x.parent = y

    def rotate_right(self, x):
        y = x.left
        x.left = y.right

        if y.right:
            y.right.parent = x

        y.parent = x.parent

        if x.parent is None:
            self.root = y
        elif x == x.parent.right:
            x.parent.right = y
        else:
            x.parent.left = y

        y.right = x
        x.parent = y

    def insert(self, data):
        new_node = Node(data)

        y = None
        x = self.root

        while x:
            y = x
            if new_node.data < x.data:
                x = x.left
            else:
                x = x.right

        new_node.parent = y

        if y is None:
            self.root = new_node
        elif new_node.data < y.data:
            y.left = new_node
        else:
            y.right = new_node

        self.fix_insert(new_node)

    def fix_insert(self, z):
        while z != self.root and z.parent.color == "RED":

            if z.parent == z.parent.parent.left:
                y = z.parent.parent.right

                if y and y.color == "RED":
                    z.parent.color = "BLACK"
                    y.color = "BLACK"
                    z.parent.parent.color = "RED"
                    z = z.parent.parent

                else:
                    if z == z.parent.right:
                        z = z.parent
                        self.rotate_left(z)

                    z.parent.color = "BLACK"
                    z.parent.parent.color = "RED"
                    self.rotate_right(z.parent.parent)

            else:
                y = z.parent.parent.left

                if y and y.color == "RED":
                    z.parent.color = "BLACK"
                    y.color = "BLACK"
                    z.parent.parent.color = "RED"
                    z = z.parent.parent

                else:
                    if z == z.parent.left:
                        z = z.parent
                        self.rotate_right(z)

                    z.parent.color = "BLACK"
                    z.parent.parent.color = "RED"
                    self.rotate_left(z.parent.parent)

        self.root.color = "BLACK"

    def inorder(self, node):
        if node:
            self.inorder(node.left)
            print(node.data, node.color)
            self.inorder(node.right)


rbt = RedBlackTree()

rbt.insert(10)
rbt.insert(20)
rbt.insert(30)
rbt.insert(15)
rbt.insert(25)

print("Isi Red-Black Tree:")
rbt.inorder(rbt.root)