# -*- coding: utf-8 -*-
"""Praktikum5RafaAgilMahendra_G.211.25.0056.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AKQXdK8dzeFiiNq6TUf_jvzVG4LurKMU

1. Pseudocode
BubbleSort(A, n)
for i = 0 to n-1
    for j = 0 to n-i-2
        if A[j] > A[j+1]
            tukar A[j] dan A[j+1]
"""

def bubble_sort(data):
    n = len(data)

    for i in range(n):
        for j in range(n - i - 1):
            if data[j] > data[j + 1]:
                data[j], data[j + 1] = data[j + 1], data[j]

    return data


angka = [64, 34, 25, 12, 22, 11, 90]

print("Sebelum sorting:", angka)
bubble_sort(angka)
print("Sesudah sorting:", angka)

"""2. Pseudocode
SelectionSort(A, n)
for i = 0 to n-2
    min = i

    for j = i+1 to n-1
        if A[j] < A[min]
            min = j

    tukar A[i] dan A[min]

Best Case: O(n²)
Average Case: O(n²)
Worst Case: O(n²)
Space Complexity: O(1)
"""

def selection_sort(data):
    n = len(data)

    for i in range(n):
        min_index = i

        for j in range(i + 1, n):
            if data[j] < data[min_index]:
                min_index = j

        data[i], data[min_index] = data[min_index], data[i]

    return data


angka = [64, 25, 12, 22, 11]

print("Sebelum sorting:", angka)
selection_sort(angka)
print("Sesudah sorting:", angka)

"""3. Pseudocode
InsertionSort(A, n)
for i = 1 to n-1
    key = A[i]
    j = i - 1

    while j >= 0 dan A[j] > key
        A[j+1] = A[j]
        j = j - 1

    A[j+1] = key

Best Case: O(n)
Average Case: O(n²)
Worst Case: O(n²)
Space Complexity: O(1)
"""

def insertion_sort(data):
    for i in range(1, len(data)):
        key = data[i]
        j = i - 1

        while j >= 0 and data[j] > key:
            data[j + 1] = data[j]
            j -= 1

        data[j + 1] = key

    return data


angka = [12, 11, 13, 5, 6]

print("Sebelum sorting:", angka)
insertion_sort(angka)
print("Sesudah sorting:", angka)

"""4. Pseudocode
MergeSort(A)
jika panjang A > 1
    bagi A menjadi kiri dan kanan

    MergeSort(kiri)
    MergeSort(kanan)

    gabungkan kiri dan kanan
    dalam urutan terurut

Best Case: O(n log n)
Average Case: O(n log n)
Worst Case: O(n log n)
Space Complexity: O(n)
"""

def merge_sort(data):
    if len(data) > 1:
        tengah = len(data) // 2

        kiri = data[:tengah]
        kanan = data[tengah:]

        merge_sort(kiri)
        merge_sort(kanan)

        i = 0
        j = 0
        k = 0

        while i < len(kiri) and j < len(kanan):
            if kiri[i] < kanan[j]:
                data[k] = kiri[i]
                i += 1
            else:
                data[k] = kanan[j]
                j += 1
            k += 1

        while i < len(kiri):
            data[k] = kiri[i]
            i += 1
            k += 1

        while j < len(kanan):
            data[k] = kanan[j]
            j += 1
            k += 1

    return data


angka = [38, 27, 43, 3, 9, 82, 10]

print("Sebelum sorting:", angka)
merge_sort(angka)
print("Sesudah sorting:", angka)